### ISSUE TITLE
cmd/acme: panic switching between fonts

### ISSUE THREAD

**Issue by amntletta** [9fans/go#104]
Using `Font` causes acme to crash when changing from a fixed font to a variable width font.

`
panic: fixi

goroutine 13 [running]:
9fans.net/go/cmd/acme/internal/adraw.FindFont(0x7c?, 0x0?, 0x0?, {0x140000d8060?, 0x1f?})
	/usr/local/plan9/go/cmd/acme/internal/adraw/font.go:31 +0x66c
9fans.net/go/cmd/acme/internal/ui.Fontx(0x140007f4000?, 0x1f?, 0x140007f4000?, 0x24?, 0x0?, {0x140007f4014?, 0x24?, 0x24?})
	/usr/local/plan9/go/cmd/acme/internal/ui/arg.go:71 +0x340
9fans.net/go/cmd/acme/internal/exec.Execute(0x14000b34010, 0x24, 0x24, 0x0, 0x0?)
	/usr/local/plan9/go/cmd/acme/internal/exec/exec.go:221 +0x930
main.mousethread()
	/usr/local/plan9/go/cmd/acme/acme.go:568 +0xc80
created by main.main
	/usr/local/plan9/go/cmd/acme/acme.go:218 +0xf80`
`

**Comment by pedramos** [comment]
I think I have a fix for this in my repo. 
https://github.com/pedramos/9fans/commit/90248db1713143f03cc4dbcb40f3d1a05115e9e8

Or the patch version:
https://github.com/pedramos/9fans/commit/90248db1713143f03cc4dbcb40f3d1a05115e9e8.patch

I don't know if the code is any good but it does seem to work in my machine.
