### ISSUE TITLE
sam: panic on opening window for plumber file

### ISSUE THREAD

**Issue by nicolagi** [9fans/go#49]
Steps to repro:

1. open sam
2. open 9term
3. B /dev/null (say) in 9term
4. go to sam, click b3

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.externchar(...)
        /mnt/muscle/src/9fans-go/cmd/samterm/io.go:165
main.kbdchar(0xd8)
        /mnt/muscle/src/9fans-go/cmd/samterm/io.go:200 +0x2cc
main.ktype(0x6bca30, 0x3)
        /mnt/muscle/src/9fans-go/cmd/samterm/main.go:534 +0xd3
main.main()
        /mnt/muscle/src/9fans-go/cmd/samterm/main.go:101 +0x534
```

**Comment by rsc** [comment]
Fixed, thanks!
