### ISSUE TITLE
sam: crash when piping text into command

### ISSUE THREAD

**Issue by fhs** [9fans/go#53]
```
$ sam -d
 -. 
|sort
panic: interface conversion: io.WriteCloser is *exec.closeOnce, not *os.File [recovered]
	panic: interface conversion: io.WriteCloser is *exec.closeOnce, not *os.File

goroutine 1 [running]:
main.main.func2.1()
	/home/fhs/go/pkg/mod/9fans.net/go@v0.0.5-0.20210417153312-d049aee7af2f/cmd/sam/sam.go:125 +0x72
panic(0x5077e0, 0xc000102750)
	/home/big/go/src/runtime/panic.go:1031 +0x25b
main.plan9(0xc000152000, 0x7c, 0xc000110048, 0xc000152000, 0xc0001026c0)
	/home/fhs/go/pkg/mod/9fans.net/go@v0.0.5-0.20210417153312-d049aee7af2f/cmd/sam/shell.go:72 +0x72c
main.plan9_cmd(0xc000152000, 0xc000124280, 0x0)
	/home/fhs/go/pkg/mod/9fans.net/go@v0.0.5-0.20210417153312-d049aee7af2f/cmd/sam/xec.go:294 +0x4d
main.cmdexec(0xc000152000, 0xc000124280, 0x0)
	/home/fhs/go/pkg/mod/9fans.net/go@v0.0.5-0.20210417153312-d049aee7af2f/cmd/sam/xec.go:64 +0x5be
main.cmdloop()
	/home/fhs/go/pkg/mod/9fans.net/go@v0.0.5-0.20210417153312-d049aee7af2f/cmd/sam/cmd.go:257 +0x92
main.main.func2()
	/home/fhs/go/pkg/mod/9fans.net/go@v0.0.5-0.20210417153312-d049aee7af2f/cmd/sam/sam.go:127 +0x45
main.main()
	/home/fhs/go/pkg/mod/9fans.net/go@v0.0.5-0.20210417153312-d049aee7af2f/cmd/sam/sam.go:130 +0x84a
```

**Comment by rsc** [comment]
Whoops, that rev fixed #54 not this one.
